// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-xttensixwh \
// RUN:   -emit-llvm %s -o - | FileCheck %s

//===----------------------------------------------------------------------===//
// Generic raw-immediate builtin (retained)
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_insn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.insn(i32 33554432)
// CHECK-NEXT:    ret void
//
void test_tt_insn(void) {
    __builtin_riscv_tt_insn(0x02000000);
}

//===----------------------------------------------------------------------===//
// Generic runtime-operand builtin (data-staging instructions)
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_insn_rt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[WORD_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[WORD:%.*]], ptr [[WORD_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[WORD_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.riscv.tt.insn.rt(i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
void test_tt_insn_rt(unsigned word) {
    __builtin_riscv_tt_insn_rt(word);
}

//===----------------------------------------------------------------------===//
// Frontend/Control
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_nop(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.nop()
// CHECK-NEXT:    ret void
//
void test_tt_nop(void) {
    __builtin_riscv_tt_nop();
}

// CHECK-LABEL: @test_tt_mop(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.mop(i32 65535, i32 127, i32 1)
// CHECK-NEXT:    ret void
//
void test_tt_mop(void) {
    __builtin_riscv_tt_mop(65535, 127, 1);
}

// CHECK-LABEL: @test_tt_replay(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.replay(i32 1, i32 1, i32 63, i32 31)
// CHECK-NEXT:    ret void
//
void test_tt_replay(void) {
    __builtin_riscv_tt_replay(1, 1, 63, 31);
}

//===----------------------------------------------------------------------===//
// Matrix Unit (FPU)
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_mvmul(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.mvmul(i32 5, i32 2, i32 1, i32 0, i32 1)
// CHECK-NEXT:    ret void
//
void test_tt_mvmul(void) {
    __builtin_riscv_tt_mvmul(5, 2, 1, 0, 1);
}

// CHECK-LABEL: @test_tt_elwadd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.elwadd(i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_tt_elwadd(void) {
    __builtin_riscv_tt_elwadd(0, 0, 0, 0, 0, 0, 0);
}

//===----------------------------------------------------------------------===//
// Data Movement
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_trnspsrcb(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.trnspsrcb()
// CHECK-NEXT:    ret void
//
void test_tt_trnspsrcb(void) {
    __builtin_riscv_tt_trnspsrcb();
}

//===----------------------------------------------------------------------===//
// Unpacker/Misc — max arity (13 args)
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_setrwc(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.setrwc(i32 1, i32 0, i32 1, i32 0, i32 5, i32 3, i32 7, i32 1, i32 0, i32 1, i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret void
//
void test_tt_setrwc(void) {
    __builtin_riscv_tt_setrwc(1, 0, 1, 0, 5, 3, 7, 1, 0, 1, 0, 0, 1);
}

//===----------------------------------------------------------------------===//
// Packer/Unpacker — multi-mode
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_unpacr(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.unpacr(i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret void
//
void test_tt_unpacr(void) {
    __builtin_riscv_tt_unpacr(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}

// CHECK-LABEL: @test_tt_unpacr_ctxinc(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.unpacr.ctxinc(i32 1)
// CHECK-NEXT:    ret void
//
void test_tt_unpacr_ctxinc(void) {
    __builtin_riscv_tt_unpacr_ctxinc(1);
}

// CHECK-LABEL: @test_tt_unpacr_flush(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.unpacr.flush(i32 1, i32 0)
// CHECK-NEXT:    ret void
//
void test_tt_unpacr_flush(void) {
    __builtin_riscv_tt_unpacr_flush(1, 0);
}

//===----------------------------------------------------------------------===//
// Configuration — multi-mode
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_setdmareg(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.setdmareg(i32 10, i32 4660)
// CHECK-NEXT:    ret void
//
void test_tt_setdmareg(void) {
    __builtin_riscv_tt_setdmareg(10, 4660);
}

// CHECK-LABEL: @test_tt_setdmareg_special(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.setdmareg.special(i32 10, i32 3, i32 5, i32 7, i32 2)
// CHECK-NEXT:    ret void
//
void test_tt_setdmareg_special(void) {
    __builtin_riscv_tt_setdmareg_special(10, 3, 5, 7, 2);
}

//===----------------------------------------------------------------------===//
// DMA Register Arithmetic
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_adddmaregi(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.adddmaregi(i32 1, i32 2, i32 3)
// CHECK-NEXT:    ret void
//
void test_tt_adddmaregi(void) {
    __builtin_riscv_tt_adddmaregi(1, 2, 3);
}

//===----------------------------------------------------------------------===//
// SFPU Vector Unit
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_sfpmad(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.sfpmad(i32 0, i32 1, i32 2, i32 3, i32 4)
// CHECK-NEXT:    ret void
//
void test_tt_sfpmad(void) {
    __builtin_riscv_tt_sfpmad(0, 1, 2, 3, 4);
}

// CHECK-LABEL: @test_tt_sfpnop(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.sfpnop()
// CHECK-NEXT:    ret void
//
void test_tt_sfpnop(void) {
    __builtin_riscv_tt_sfpnop();
}

//===----------------------------------------------------------------------===//
// Sync/Semaphore
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_stallwait(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.stallwait(i32 255, i32 511)
// CHECK-NEXT:    ret void
//
void test_tt_stallwait(void) {
    __builtin_riscv_tt_stallwait(255, 511);
}

// CHECK-LABEL: @test_tt_seminit(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.seminit(i32 1, i32 0, i32 15)
// CHECK-NEXT:    ret void
//
void test_tt_seminit(void) {
    __builtin_riscv_tt_seminit(1, 0, 15);
}

//===----------------------------------------------------------------------===//
// Config Read/Write
//===----------------------------------------------------------------------===//

// CHECK-LABEL: @test_tt_setc16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.tt.setc16(i32 100, i32 5)
// CHECK-NEXT:    ret void
//
void test_tt_setc16(void) {
    __builtin_riscv_tt_setc16(100, 5);
}
